# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'the_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1360, 949)
        MainWindow.setStyleSheet("background-image: url(:/media/main_background.png);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 290, 131, 31))
        self.pushButton.setStyleSheet("background-image: url(:/media/white.png);\n"
"font: 9pt \"宋体\";")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 170, 101, 31))
        self.label.setStyleSheet("background-image: url(:/media/white.png);\n"
"font: 9pt \"宋体\";")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 290, 131, 31))
        self.pushButton_2.setStyleSheet("background-image: url(:/media/white.png);\n"
"font: 9pt \"宋体\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(680, 290, 131, 31))
        self.pushButton_3.setStyleSheet("background-image: url(:/media/white.png);\n"
"font: 9pt \"宋体\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(850, 290, 131, 31))
        self.pushButton_4.setStyleSheet("background-image: url(:/media/white.png);\n"
"font: 9pt \"宋体\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(530, 170, 201, 31))
        self.lineEdit.setStyleSheet("background-image: url(:/media/white.png);")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(560, 790, 131, 31))
        self.pushButton_5.setStyleSheet("background-image: url(:/media/white.png);\n"
"font: 9pt \"宋体\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(530, 690, 201, 31))
        self.lineEdit_2.setStyleSheet("background-image: url(:/media/white.png);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 690, 181, 31))
        self.label_2.setStyleSheet("background-image: url(:/media/white.png);\n"
"font: 9pt \"宋体\";")
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 450, 131, 31))
        self.label_3.setStyleSheet("background-image: url(:/media/white.png);\n"
"font: 9pt \"宋体\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(530, 450, 201, 31))
        self.lineEdit_3.setStyleSheet("background-image: url(:/media/white.png);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(560, 560, 131, 31))
        self.pushButton_6.setStyleSheet("background-image: url(:/media/white.png);\n"
"font: 9pt \"宋体\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 380, 1361, 20))
        self.label_4.setStyleSheet("background-image: url(:/media/white.png);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 620, 1361, 20))
        self.label_5.setStyleSheet("background-image: url(:/media/white.png);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, 850, 1361, 20))
        self.label_6.setStyleSheet("background-image: url(:/media/white.png);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(0, 100, 1361, 20))
        self.label_7.setStyleSheet("background-image: url(:/media/white.png);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(360, 20, 651, 51))
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setStyleSheet("background-image: url(:/media/white.png);\n"
"font: 20pt \"华文行楷\";")
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(960, 450, 331, 141))
        self.textBrowser.setStyleSheet("background-image: url(:/media/white.png);")
        self.textBrowser.setObjectName("textBrowser")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(830, 450, 91, 31))
        self.label_9.setStyleSheet("background-image: url(:/media/white.png);\n"
"font: 9pt \"宋体\";")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "微博舆情分析软件"))
        self.pushButton.setText(_translate("MainWindow", "开始爬虫"))
        self.label.setText(_translate("MainWindow", "话题"))
        self.pushButton_2.setText(_translate("MainWindow", "情感分析"))
        self.pushButton_3.setText(_translate("MainWindow", "统计关键字"))
        self.pushButton_4.setText(_translate("MainWindow", "可视化"))
        self.pushButton_5.setText(_translate("MainWindow", "水军攻击"))
        self.label_2.setText(_translate("MainWindow", "攻击微博数量"))
        self.label_3.setText(_translate("MainWindow", "多模式匹配"))
        self.pushButton_6.setText(_translate("MainWindow", "多模式匹配"))
        self.label_4.setText(_translate("MainWindow", "*************************************************************************************************************************************"))
        self.label_5.setText(_translate("MainWindow", "*************************************************************************************************************************************"))
        self.label_6.setText(_translate("MainWindow", "*************************************************************************************************************************************"))
        self.label_7.setText(_translate("MainWindow", "*************************************************************************************************************************************"))
        self.label_8.setText(_translate("MainWindow", "欢迎使用微博舆情分析系统"))
        self.label_9.setText(_translate("MainWindow", "结果"))
import resource_rc
